pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { 
            url 'https://maven.pkg.github.com/arthenica/ffmpeg-kit'
            // เพิ่มส่วนนี้เพื่อดึงไลบรารีของ ffmpeg-kit โดยตรง
        }
        maven { url 'https://repo1.maven.org/maven2/' }
    }
}

rootProject.name = "Mcuteditor Pro"
include ':app'
